[package]
name = "trdelnik-client"
version = "0.1.0"
edition = "2018"
authors = ["AckeeBlockchain <hello@ackeeblockchain.com>>"]
license = "Apache-2.0"
repository = "https://github.com/Ackee-Blockchain/trdelnik"
description = "Rust testing client for Anchor programs"

[build-dependencies]
vergen = { version = "6", features = ["build", "git"], default-features = false }
anyhow = { version = "1.0.45", features = ["std"], default-features = false }

[dev-dependencies]
pretty_assertions = "1.1.0"

[dependencies]
trdelnik-test = "0.1.0"
solana-sdk = "~1.9"
solana-cli-output = "~1.9"
solana-transaction-status = "~1.9"
anchor-client = "0.24.2"
spl-token = "3.2.0"
spl-associated-token-account = "1.0.3"
tokio = { version = "1.13.0", features = ["rt-multi-thread", "macros", "fs", "signal", "sync", "time", "io-util", "process"], default-features = false }
rand = "0.7.3"
serde_json = "1.0.72"
serde = "1.0.136"
bincode = "1.3.3"
borsh = "0.9.3"
futures = "0.3.18"
fehler = { version = "1.0.0", default-features = false }
thiserror = "1.0.30"
ed25519-dalek = "1.0.1"
serial_test = "0.5.1"
anyhow = { version = "1.0.45", features = ["std"], default-features = false }
cargo_metadata = "0.14.1"
syn = "1.0.85"
quote = "1.0.14"
heck = { version = "0.4.0", default-features = false }
toml = { version = "0.5.8", features = ["preserve_order"] }
log = "0.4"
rstest = "0.12.0"
